### ISSUE TITLE
updateSystems doesn't seem to be actually pushing data

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/Canonn-EDSM-Updater#11]
Tested with both build and dev commands using the newly updated staging server, it appears that the updater is getting data from EDSM but isn't pushing the data to the API.

If the updater is trying to send nested PUT requests that would be the reason, each system will need to be updated in a single PUT request.

Based on the following code:
https://github.com/canonn-science/CAPIv2-Updater/blob/115f1f725cb1a1976228638d2aad99ac5716512d/src/api/canonn.js#L153-L170

It looks like it might be trying to push a payload then querying each system one by one afterwords.

**Comment by coldwhitelight** [comment]
Fixed with #12
