### ISSUE TITLE
Body lookup fails if System/Body name contains a "+" symbol

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/Canonn-EDSM-Updater#14]
It looks like the url encoder isn't properly encoding the + symbol in a body name thus EDSM returns zero results: 

https://www.edsm.net/api-system-v1/bodies?systemName=BD+38%202037
https://www.edsm.net/en/system/bodies/id/18383/name/BD%2B38+2037/details/idB/663256/nameB/BD%2B38+2037+A+1

**Comment by coldwhitelight** [comment]
This is fixed (and tested) as of https://github.com/canonn-science/CAPIv2-Updater/commit/d1f32f06cecc6b7a4672fe0da2d5809ddf70b3da

**Comment by derrickmehaffy** [comment]
cool marking as closed
