### ISSUE TITLE
Track updates for all updated fields/scripts

### ISSUE THREAD

**Issue by coldwhitelight** [canonn-science/Canonn-EDSM-Updater#15]
This is an extension of #8 that renders it obsolete.

The script should track updates of all changed fields, not only system/body, since the updater role has been expanded.

Changes will be tracked in the updateLog field of apiupdates in CAPI.
@derrickmehaffy You can safely remove "updatedSystems" and "updatedBodies" from apiupdates model. Everything will be stored in "updateLog".

**Comment by derrickmehaffy** [comment]
Fixed in: https://github.com/canonn-science/CAPIv2-Strapi/commit/78a550b6bca3687eab928a8e25a9e36878d298d6
