### ISSUE TITLE
Add an option to query EDSM for a specific System or Body

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/Canonn-EDSM-Updater#2]
Updater should include the ability to query EDSM for a single Body or System based on the ID

Something like `npm run updateSystem 1` or `npm run updateBody 1` where 1 is the Canonn `id`

This would allow us to build and run this updater within the CAPIv2 to allow for a "protected" route (requiring authentication) such as `GET https://api.canonn.tech/updateSystem/1` to allow for easy updating of systems and/or bodies.

**Comment by coldwhitelight** [comment]
Solved by: #5

**Comment by derrickmehaffy** [comment]
PR merged, resolving
